### ISSUE TITLE
pytesseract调用错误

### ISSUE THREAD

**Issue by Sciroccogti** [wolverinn/seu_GPACalculator#1]
似乎已经将参数`-psm`更新为`--psm`

另外增加了自动登录的版本反而输出错误，获取的数值均为0；然而旧版能够正常输出

Anyway，感谢！

**Comment by wolverinn** [comment]
多谢，我还是把新版本去掉吧，感觉Tesseract OCR识别准确率有点低了~
谢谢pull requests

**Comment by Sciroccogti** [comment]
忘了修改comment了233抱歉~
之前好像是我OCR使用有误，现在感觉识别率倒是还不错的呢
